import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const clashGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/ClashGrotesk-Light.woff2",
      weight: "300", // Light
      style: "normal",
    },
    {
      path: "../public/fonts/ClashGrotesk-Regular.woff2",
      weight: "400", // Regular
      style: "normal",
    },
    {
      path: "../public/fonts/ClashGrotesk-Medium.woff2",
      weight: "500", // Medium
      style: "normal",
    },
  ],
  variable: "--font-clash-grotesk",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${clashGrotesk.variable} `}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}